Added npm runner

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,6 +8,18 @@ indent() {
   sed -u 's/^/       /'
 }
 
+function run_npm() {
+  command="$1"
+
+  cd $BUILD_DIR
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi
+}
+
 # config
 APACHE_VERSION="2.2.22"
 APACHE_PATH="apache"
@@ -18,14 +30,14 @@ BIN_DIR=$(dirname $0)
 BUILD_DIR=$1
 CACHE_DIR=$2
 LP_DIR=`cd $(dirname $0); cd ..; pwd`
+VENDORED_NODE="$(mktmpdir node)"
+VENDORED_NPM="$(mktmpdir npm)"
 
 export LANG=en_US.UTF-8
 
 # INSTALL LIBRARIES AND COMPILE ASSETS
 # Code borrowed from: https://github.com/abhishekmunie/heroku-buildpack-static-css
 # --------------------------------------------------------------------------------
-
-
 echo "       WARNING: This deploy process depends on heroku lab feature making config vars availible during build."
 echo "       See: https://devcenter.heroku.com/articles/labs-user-env-compile"
 
@@ -40,6 +52,8 @@ if [ -f $BUILD_DIR/package.json ]; then
 	echo "done." | indent
 
 	export PATH=$PATH:$NODE_BUILD_DIR/bin:$NODE_BUILD_DIR/node_modules/.bin
+
+	run_npm "install grunt-cli"
 
 	$BUILD_DIR/node_modules/grunt-cli/bin/grunt heroku
 fi
